/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 * @author Isabel Higuita Giraldo
 */

import poo_ejercicio_18.Employee;
import poo_ejercicio_18.Salary;
import javax.swing.JOptionPane;
import java.awt.CardLayout;

public class Interface extends javax.swing.JFrame {

    // Attributes
    
    private Employee employee;
    private Salary salary;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCardLayout = new javax.swing.JPanel();
        panelCreateEmployee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JTextField();
        submitEmployee = new javax.swing.JButton();
        panelCalculateSalary = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        salaryCode = new javax.swing.JTextField();
        salaryName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salaryPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldHours = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldPercent = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        submitSalary = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelViewResult = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        resultCode = new javax.swing.JTextField();
        resultName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        resultPrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        resultHours = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        resultBruto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        resultPercent = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        resultNeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCardLayout.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleado");

        fieldCode.setToolTipText("Ingrese un número entero positivo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel3.setText("Nombre Completo");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel11.setText("Valor por Hora");

        jLabel12.setText("$");

        fieldPrice.setToolTipText("Ingrese un número decimal positivo separado por punto (.)");

        submitEmployee.setText("Guardar");
        submitEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateEmployeeLayout = new javax.swing.GroupLayout(panelCreateEmployee);
        panelCreateEmployee.setLayout(panelCreateEmployeeLayout);
        panelCreateEmployeeLayout.setHorizontalGroup(
            panelCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCode, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldName)
                    .addGroup(panelCreateEmployeeLayout.createSequentialGroup()
                        .addGroup(panelCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCreateEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPrice)))
                .addContainerGap())
            .addGroup(panelCreateEmployeeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(submitEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCreateEmployeeLayout.setVerticalGroup(
            panelCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCardLayout.add(panelCreateEmployee, "card2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Empleado");

        salaryCode.setEditable(false);
        salaryCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salaryCode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        salaryCode.setText("code");
        salaryCode.setBorder(null);

        salaryName.setEditable(false);
        salaryName.setText("name");
        salaryName.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel6.setText("Valor por Hora");

        salaryPrice.setEditable(false);
        salaryPrice.setText("hourPrice");
        salaryPrice.setBorder(null);

        jLabel7.setText("$");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Salario");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel9.setText("Horas Trabajadas");

        fieldHours.setToolTipText("Ingrese un número entero positivo");

        fieldPercent.setToolTipText("Ingrese un número decimal positivo separado por punto (.)");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel13.setText("Porcentaje de Retención");

        submitSalary.setText("Calcular");
        submitSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSalaryActionPerformed(evt);
            }
        });

        jLabel14.setText("%");

        javax.swing.GroupLayout panelCalculateSalaryLayout = new javax.swing.GroupLayout(panelCalculateSalary);
        panelCalculateSalary.setLayout(panelCalculateSalaryLayout);
        panelCalculateSalaryLayout.setHorizontalGroup(
            panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalculateSalaryLayout.createSequentialGroup()
                .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCalculateSalaryLayout.createSequentialGroup()
                        .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCalculateSalaryLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(submitSalary))
                            .addGroup(panelCalculateSalaryLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCalculateSalaryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldHours)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCalculateSalaryLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(salaryCode, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .addComponent(salaryName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCalculateSalaryLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCalculateSalaryLayout.createSequentialGroup()
                                .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelCalculateSalaryLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14))
                            .addGroup(panelCalculateSalaryLayout.createSequentialGroup()
                                .addComponent(fieldPercent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))))
                .addContainerGap())
        );
        panelCalculateSalaryLayout.setVerticalGroup(
            panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculateSalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(salaryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salaryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitSalary)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelCardLayout.add(panelCalculateSalary, "card3");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Empleado");

        resultCode.setEditable(false);
        resultCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resultCode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultCode.setText("code");
        resultCode.setBorder(null);

        resultName.setEditable(false);
        resultName.setText("name");
        resultName.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel16.setText("Nombre");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel17.setText("Valor por Hora");

        resultPrice.setEditable(false);
        resultPrice.setText("hourPrice");
        resultPrice.setBorder(null);

        jLabel18.setText("$");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Salario");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel20.setText("Horas");

        resultHours.setEditable(false);
        resultHours.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultHours.setText("hourWorked");
        resultHours.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel21.setText("Salario Bruto");

        resultBruto.setEditable(false);
        resultBruto.setText("salarioBruto");
        resultBruto.setBorder(null);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel22.setText("Salario Neto");

        resultPercent.setEditable(false);
        resultPercent.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        resultPercent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultPercent.setText("rete");
        resultPercent.setBorder(null);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel23.setText("%");

        resultNeto.setEditable(false);
        resultNeto.setText("salarioNeto");
        resultNeto.setBorder(null);

        javax.swing.GroupLayout panelViewResultLayout = new javax.swing.GroupLayout(panelViewResult);
        panelViewResult.setLayout(panelViewResultLayout);
        panelViewResultLayout.setHorizontalGroup(
            panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultNeto)
                    .addComponent(resultBruto)
                    .addComponent(jSeparator2)
                    .addGroup(panelViewResultLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(resultCode))
                    .addComponent(resultName)
                    .addGroup(panelViewResultLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultPrice))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewResultLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewResultLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultPercent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(panelViewResultLayout.createSequentialGroup()
                        .addGroup(panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel21))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelViewResultLayout.setVerticalGroup(
            panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(resultCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(resultHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(resultPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelCardLayout.add(panelViewResult, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEmployeeActionPerformed
        
        try {
            int code = Integer.parseInt(fieldCode.getText());
            String name = fieldName.getText();
            int price = Integer.parseInt(fieldPrice.getText());

            this.employee = new Employee(code, name, price);

            CardLayout cardLayout = (CardLayout) panelCardLayout.getLayout();
            cardLayout.show(panelCardLayout, "card3");

            salaryCode.setText(String.valueOf(code));
            salaryName.setText(name);
            salaryPrice.setText(String.valueOf(price));
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los valores ingresados no son válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitEmployeeActionPerformed

    private void submitSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSalaryActionPerformed
        
        try {
            int hours = Integer.parseInt(fieldHours.getText());
            double percent = Double.parseDouble(fieldPercent.getText());

            this.salary = new Salary(this.employee, hours, percent);

            double salaryBruto = this.salary.getSalaryBruto();
            double salaryNeto = this.salary.getSalaryNeto();

            CardLayout cardLayout = (CardLayout) panelCardLayout.getLayout();
            cardLayout.show(panelCardLayout, "card4");

            String name = this.employee.getName();
            int code = this.employee.getCode();
            double price = this.employee.getHourPrice();

            resultCode.setText(String.valueOf(code));
            resultName.setText(name);
            resultPrice.setText(Double.toString(price));

            resultHours.setText(String.valueOf(hours));
            resultPercent.setText("-" + Double.toString(percent));
            resultBruto.setText(Double.toString(salaryBruto));
            resultNeto.setText(Double.toString(salaryNeto));
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los valores ingresados no son válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitSalaryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCode;
    private javax.swing.JTextField fieldHours;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPercent;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelCalculateSalary;
    private javax.swing.JPanel panelCardLayout;
    private javax.swing.JPanel panelCreateEmployee;
    private javax.swing.JPanel panelViewResult;
    private javax.swing.JTextField resultBruto;
    private javax.swing.JTextField resultCode;
    private javax.swing.JTextField resultHours;
    private javax.swing.JTextField resultName;
    private javax.swing.JTextField resultNeto;
    private javax.swing.JTextField resultPercent;
    private javax.swing.JTextField resultPrice;
    private javax.swing.JTextField salaryCode;
    private javax.swing.JTextField salaryName;
    private javax.swing.JTextField salaryPrice;
    private javax.swing.JButton submitEmployee;
    private javax.swing.JButton submitSalary;
    // End of variables declaration//GEN-END:variables
}
